# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
  pod 'Alamofire', '~>  4.8.1'
end

target 'SuperArticles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SuperArticles
  shared_pods

  target 'SuperArticlesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SuperArticlesUITests' do
    # Pods for testing
  end

end
